version: 2
jobs:
    build-duo-contract-wrapper:
        working_directory: /home/circleci/duo-contract-wrapper
        docker: 
            - image: circleci/node:8.11.1
        steps:
            - run: git clone https://github.com/FinBook/duo-contract-wrapper.git /home/circleci/duo-contract-wrapper
            - run: cd /home/circleci/duo-contract-wrapper
            - restore_cache:
                key: dependency-cache-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                name: Install npm wee
                command: npm install
            - save_cache:
                key: dependency-cache-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - /home/circleci/duo-contract-wrapper
    build-duo-admin:
        working_directory: /home/circleci/duo-admin
        docker: 
            - image: circleci/node:8.11.1
        steps:
            - run: git clone https://github.com/FinBook/duo-admin.git /home/circleci/duo-admin
            - run: cd /home/circleci/duo-admin
            - restore_cache:
                key: dependency-assets-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                name: Install npm wee
                command: npm install
            - save_cache:
                key: dependency-assets-{{ .Environment.CIRCLE_SHA1 }}
                path: /home/circleci/duo-admin
    build-israfel-relayer:
        working_directory: /home/circleci/israfel-relayer
        docker: 
            - image: circleci/node:8.11.1
        steps:
            - add_ssh_keys:
                fingerprints:
                    - "b7:35:a6:4e:9b:0d:6d:d4:78:1e:9a:97:2a:66:6b:be"
                    - "7a:0d:dd:1b:85:8a:34:d9:3e:99:b1:49:db:fb:e4:6e"
                    - "c4:57:14:a4:83:f3:ca:f3:60:97:4f:04:10:e9:65:59"
                    - "16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48"
                    - "e6:90:fa:e5:7d:4e:7e:d7:2f:ed:d0:5b:3a:b6:77:cb"
                    - "3d:80:45:8e:e6:d2:fd:fd:9b:94:73:80:b3:6c:3e:c2"
                    - "aa:42:83:37:be:c6:3c:db:68:f6:25:90:3b:24:b5:a5"
            - run: rm /home/.ssh/id_rsa
            - run: rm /home/.ssh/id_rsa.pub
            - run:
                name: upload files to github
                command: |
                    echo '192.30.253.113 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/' >> ~/.ssh/known_hosts
                    ssh git@192.30.253.113 sudo scp -r FinBook/israfel-relayer/* git@192.30.253.113:~/circleupload
            - run: git clone git@github.com:FinBook/israfel-relayer.git /home/circleci/israfel-relayer
            - run: cd /home/circleci/israfel-relayer
            - restore_cache:
                key: dependency-relayer-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                name: Install npm wee
                command: npm install
            - save_cache:
                key: dependency-relayer-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - /home/circleci/israfel-relayer
    test:
        working_directory: /home/circleci/israfel-app
        docker:
            - image: circleci/node:8.11.1
        steps:
            - checkout
            - restore_cache:
                key: dependency-relayer-{{ .Environment.CIRCLE_SHA1 }}
            - restore_cache:
                key: dependency-cache-{{ .Environment.CIRCLE_SHA1 }}
            - restore_cache:
                key: dependency-assets-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                name: Install npm
                command: npm install
            - run:
                name: test
                command: npm test -- -w 1
workflows:
    version: 2
    build_and_test:
        jobs:
            - build-duo-contract-wrapper
            - build-duo-admin
            - build-israfel-relayer
            - test:
                requires:
                    - build-israfel-relayer
                    - build-duo-contract-wrapper
                    - build-duo-admin
                filters:
                    branches:
                        only: master
