version: 2
jobs:
    deploy:
        docker:
            - image: circleci/python:2.7-jessie
        working_directory: /home/circleci/test
        steps:
            - run:
                name: Install awscli
                command: sudo pip install awscli
            - restore_cache:
                key: dependency-test-{{ .Environment.CIRCLE_SHA1 }}
            - run: aws s3 sync ./lcov-report s3://israfel-coverage
workflows:
    version: 2
    build_and_test:
        jobs:
            - deploy: