version: 2
jobs:
    push-repo:
        working_directory: /home/circleci/duo-network-kovan-relayer
        docker:
            - image: circleci/node:8.11.1
        steps:
            - add_ssh_keys:
                  fingerprints:
                      - '48:4b:53:58:5a:d6:34:40:e1:43:32:03:9f:85:96:bc'
            - run:
                  name: Fix host authenticity for 192.30.253.113
                  command: |
                      ssh-keyscan 192.30.253.113 >> ~/.ssh/known_hosts
            - run: git clone git@192.30.253.113:lipeiru0329/testCircleCI.git /home/circleci/duo-network-kovan-relayer/testCircleCI
            - run: git clone git@192.30.253.113:lipeiru0329/Hello_World.git /home/circleci/duo-network-kovan-relayer/Hello_World
            - run: ls
            - run: cd /home/circleci/duo-network-kovan-relayer/testCircleCI
            - run: cp -a ./testCircleCI/index.html ./Hello_World
            - add_ssh_keys:
                  fingerprints:
                      - '39:a3:74:f5:d3:fa:ca:46:14:bf:bd:8f:26:06:c6:b0'
            - run:
                  name: push
                  command: cd /home/circleci/duo-network-kovan-relayer/Hello_World
                      && git config --global user.email "lipeiru0329@gmail.com"
                      && git config --global user.name "lipeiru0329"
                      && git add *
                      && git commit -m 'update'
                      && git push -u origin master
workflows:
    version: 2
    build_test_deploy:
        jobs:
            - push-repo
