export const AC_AUTH = 'auth';

export const TH_LOGIN = "Admin Login";
export const TH_LOGOUT = "Log out";
export const TH_ACCOUNT = "Account";
export const TH_PASSWORD = "Password";
export const TH_ACCOUNT_PH = "Please input account";
export const TH_PASSWORD_PH = "Please input password";
export const TH_SUBMIT = 'Submit';
export const TH_CLEAR = 'Clear';
export const PENDING_TX_TIMEOUT = 1200000;
export const RELAYER_WS_URL = 'ws://localhost:8080';
export const TH_SUBSCRIBE = 'subscribe';
export const TH_UPDATE = 'update';
export const TH_BID = 'bid';   /************************** */
export const TH_ASK = 'ask';	/************************** */
export const TH_ORDERBOOK = 'Orderbook'; 	/***************** */
export const TH_LOADING = 'loading';
export const TH_SNAPSHOT = 'snapshot';
